services:

  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: bank_db
      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: ${BANK_DB_PASSWORD}
    volumes:
      - bank_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bank_user -d bank_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  bank-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bank_db
      SPRING_DATASOURCE_USERNAME: bank_user
      SPRING_DATASOURCE_PASSWORD: ${BANK_DB_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  bank_postgres_data: